name: home_arrest
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #network
  http: ^0.13.3
  get: ^4.6.1

  # State Management
  provider: ^6.0.4

  # UI
  path_provider: ^2.0.11
  google_fonts: ^4.0.4
  flutter_staggered_animations: ^1.1.1
  device_preview: ^1.1.0
  signature: ^5.4.1
  cached_network_image: ^3.2.3
  image_picker: ^1.0.4

  # Database
  shared_preferences: ^2.2.2

  # Maps
  google_maps_flutter: ^2.3.0
  location: ^4.3.0 


dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.17.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
